---
# Calamares settings for XanadOS
branding: xanados
modules-search:
  - /etc/calamares/modules
  - /usr/share/calamares/modules
  - /lib/calamares/modules
  - ./modules

show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - summary
  - install
  - finished

# Set default language and timezone
localeConf:
  defaultLocale: en_IE.UTF-8
  defaultTimezone: Europe/Dublin
