---
oem: true
disable-cancel: false
disable-back: false
instance-id: "XanadOS-Installer"
show-advanced: true
prompt-install: true
dont-chroot: false
secureboot: true
allow-encryption: true
modules-search: "/lib/calamares/modules"

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
      - install
      - finished

branding:
  productName: "XanadOS"
  shortProductName: "XanadOS"
  version: "1.0"
  sidebarBackground: "#111111"
  sidebarText: "#FF00FF"
  sidebarTitle: "Install XanadOS"
  imagePath: "logo.png"
  stylesheet: "style.qss"

machineid: true
