---
dont-touch-my-partitions: false
defaultFileSystemType: btrfs
defaultPartitionTableType: gpt
defaultSwap: true

partitions:
  - mountPoint: /
    filesystem: btrfs
    size: 20GiB
    encrypted: true
  - mountPoint: /boot/efi
    filesystem: fat32
    size: 300MiB
