---
# Partitioning configuration for Calamares with optional LUKS encryption
efi:
  filesystem: fat32
  mountPoint: /boot/efi
  size: 300M
  flag: boot

partitions:
  - id: luks_root
    type: luks
    luksName: luksRoot
    luksPassphrase: ""
    luksCipher: aes-xts-plain64
    luksKeySize: 512
    luksHash: sha512
    luksVolume: luksVolume
    luksFstabOptions: defaults,noatime
    fs: btrfs
    mountPoint: /
    label: root
    size: 100%
