#
# /etc/pacman.conf
#

[options]
Architecture = x86_64
HoldPkg     = pacman glibc
Color
CheckSpace
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[xanados]
SigLevel = Optional TrustAll
Server = file:///workspace/xanados/packages/repo

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
