---
automated: true
defaultFileSystemType: btrfs
alwaysKeep: false
reuseHome: false
drawNestedPartitions: true
efiSystemPartition: "/boot/efi"
enableLuks: true
luksPassphraseRequired: true
luksAllowEmptyPassphrase: false
defaultPartitionTableType: gpt
