# .github/workflows/build.yml
name: Build

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install archiso
        run: pacman -Syu --noconfirm archiso
      - name: Install sudo
        run: pacman -Syu --noconfirm sudo
      - name: Build ISO
        run: bash scripts/build_iso.sh
