# .github/workflows/build.yml
---
name: Build

"on":
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install archiso
        run: pacman -Syu --noconfirm archiso
      - name: Install sudo
        run: pacman -Syu --noconfirm sudo
      - name: Install grub
        run: pacman -Syu --noconfirm grub
      - name: Install bats
        run: pacman -Syu --noconfirm bats
      - name: Install pacman-contrib
        run: pacman -Syu --noconfirm pacman-contrib
      - name: Install required build tools
        run: pacman -Sy --noconfirm debugedit fakeroot
      - name: Create build user
        run: |
          sudo groupadd -f builduser
          sudo useradd -m -g builduser builduser || true
      - name: Grant write access to build directory
        run: sudo chown -R builduser:builduser packages
      - name: Build ISO
        run: bash scripts/build_iso.sh
